### ISSUE TITLE
Code about getting APK information

### ISSUE THREAD

**Issue by ljy-002** [F-Unction/LinspirerAppStoreEnumerator#10]
我想，如果你们愿意，可以出一个C++版
我想Py版马上会实现

**Comment by ljy-002** [comment]
不要在意上面的问题关闭，那只是提及了

**Comment by F-Unction** [comment]
你出py的整合进来就好，命令行调用的开销不一定多少，出py的我还能对着抄个c#的（

**Comment by ljlVink** [comment]
# 6

**Comment by Tonyha7** [comment]
那为啥不用aapt呢

**Comment by ljlVink** [comment]
> > 那为啥不用aapt呢
> 
> 我会发布三种到四种Py的实现方法


![7CUWD Y65STH8282 RQCFME](https://user-images.githubusercontent.com/46098706/210174379-9b30fb52-9556-477d-91d3-8601b3574495.jpg)
有必要吗？？效率高就好了

~~构建群有个`main.py`是api的，50线并发没问题~~

**Comment by ljy-002** [comment]
在Github上一般不用这种表情包 : L

**Comment by ljy-003** [comment]
我尝试了尽多的方法，但它们并不奏效
如果期末考完我有时间的话，我可以继续尝试其他办法

**Comment by ljy-002** [comment]
此问题没有被解决，在期末考试之前，我想，这个问题不会被重新打开

**Comment by ljy-002** [comment]
END
