### ISSUE TITLE
Not only download1.linspirer.com

### ISSUE THREAD

**Issue by ljy-002** [F-Unction/LinspirerAppStoreEnumerator#8]
linspirer.com子域：
api.linspirer.com	60.205.86.234
app.linspirer.com	60.205.176.16
appstore.linspirer.com	47.95.50.184
bd.linspirer.com	123.249.19.113
cloud.linspirer.com	47.95.50.184
data.linspirer.com	60.205.176.16
#### **download2.linspirer.com	120.52.95.247**
edu.linspirer.com	119.3.116.189
guard.linspirer.com 121.36.155.69
imap.linspirer.com	59.82.8.66
linspirer.com	60.205.182.110
log1.linspirer.com	124.70.126.163
mail.linspirer.com	59.82.9.177
mdm.linspirer.com	60.205.182.110
nas.linspirer.com	121.229.109.63
pop3.linspirer.com	59.82.15.82
qa.linspirer.com	139.9.121.130
qatest.linspirer.com 60.205.182.110
reg.linspirer.com	60.205.86.234
smtp.linspirer.com	59.82.14.215
test.linspirer.com	139.9.121.130

**Comment by ljy-002** [comment]
需要更多信息吗？

**Comment by ljy-002** [comment]
download1.linspirer.com
download2.linspirer.com
好像是CDN

**Comment by F-Unction** [comment]
抱歉，你repoowner在学校封了三星期，今天刚回家

**Comment by F-Unction** [comment]
虽然但是，本项目没有直接指向download1或者2，应该不会出现问题

**Comment by ljy-002** [comment]
好的

**Comment by ljy-002** [comment]
是否可以尝试download.ndwill.com或者其他linspirer.com&ndwill.com的子域？
这可能对于(平板)破解有所帮助

**Comment by F-Unction** [comment]
平板破解已经比较成熟了，本repo的目的仅仅在于”枚举商店app“

**Comment by F-Unction** [comment]
如果您有枚举其他同规则商店app的需求，可以手动更改代码中的url

**Comment by ljy-002** [comment]
好的，我想我会参考你们的储存库
我这里还有一些信息，希望有所帮助

[Linspirer.txt](https://github.com/F-Unction/LinspirerAppStoreEnumerator/files/10256095/Linspirer.txt)
这个文件依然在更新：
[ljy-002/Linspirer.txt](https://github.com/ljy-002/Linspirer.txt)

**Comment by ljy-002** [comment]
感谢你的回答~

**Comment by F-Unction** [comment]
我刚刚通过邮箱[suvgli@dingtalk.com](mailto:suvgli@dingtalk.com)联系您
